### ISSUE TITLE
Installation doc

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#1]
The installation documentation is not precise enough.
It assumes too much knowledge from the user. Example: "Use redis as a worker thread and then echo it with an event and to Laravel Echo"

**Comment by MisterX25** [comment]
Had to fight another 1/2 hour to get it working again today

**Comment by EricBroutba** [comment]
Could you please provide us more details about the bugs ?

**Comment by MisterX25** [comment]
I’m currently doing it in GitHub/Issues.

The problematic one is this debug panel on the right:
[cid:6409DC60-1226-41D8-B5BB-A85CE8F0B886]


Le 18 juil. 2017 à 10:22, Eric Broutba <notifications@github.com<mailto:notifications@github.com>> a écrit :


Could you please provide us more details about the bugs ?
