### ISSUE TITLE
Return Values on actions

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#101]
The start and stop endpoints return the modified run in response. This is good because it makes it easy on the mobile app side to refresh the display.

Please make api/runners/{runner}/driver and api/runners/{runner}/car do the same

**Comment by bastiennicoud** [comment]
Added in commit 16d95039a6796eb2dc070deabb7a87fdf667392a

**Comment by XCarrel** [comment]
I need the full run in return, because its state may have changed

**Comment by bastiennicoud** [comment]
Resolved in [v2.0.0-rc.1.5](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-rc.1.5)
