### ISSUE TITLE
Incorrect vehicle name

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#104]
The value returned in the 'name' field is brand+model, it must be the name

![capture d ecran 2018-06-20 a 14 45 11](https://user-images.githubusercontent.com/7465241/41659088-981d7b50-7498-11e8-8bf3-419935912716.png)

**Comment by bastiennicoud** [comment]
Resolved in commit 59941b7df2bb1650651174002c0bb6e08da55435
