### ISSUE TITLE
Schedules

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#106]
Still can't get the schedules up an running...

I can enter a schedule, it's created in the db.
![capture d ecran 2018-06-20 a 19 03 54](https://user-images.githubusercontent.com/7465241/41673339-f4f90c80-74bc-11e8-80c8-83c238d0b0e4.png)

But the page remains blank:
![capture d ecran 2018-06-20 a 19 03 36](https://user-images.githubusercontent.com/7465241/41673288-cbd3a4b4-74bc-11e8-90b5-5839a4dff363.png)

Assets regenerated fine for dev, fail for build:
![capture d ecran 2018-06-20 a 19 05 21](https://user-images.githubusercontent.com/7465241/41673323-e8fa56f0-74bc-11e8-9b11-3f846d1f1dfe.png)

Gotta be something with assets management:
![capture d ecran 2018-06-20 a 19 04 18](https://user-images.githubusercontent.com/7465241/41673374-0b0bd2dc-74bd-11e8-941f-cda212eb2282.png)

**Comment by bastiennicoud** [comment]
The script for generating production assets is `npm run prod`. Sorry for the inconvenience.

**Comment by XCarrel** [comment]
Problem solved by magic
