### ISSUE TITLE
Publication of incomplete run

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#11]
The system must allow to publish a run even if it is not fully defined. It's not the case in v1.0.2 which requires the run to be fully defined

**Comment by bastiennicoud** [comment]
Resolved in v2.0.0-beta.3

**Comment by bastiennicoud** [comment]
Now if you publish incomplete run, is status pass to 'needs_filling'. It can be started only with a force_start.
