### ISSUE TITLE
Create new user broken

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#112]
The create new user function doesn't work: click on the button 'Create' returns to the same page with no effect.
Workaroud: I created a dumb route `/manualcreate` that creates a 'John Doe' user that you can then edit

**Comment by Dardanboy** [comment]
Fixed in de29e2c.
The fault was into the view `user.create` that redirected to the same page in the form action.

Changed the route to go to `user.store` instead.
