### ISSUE TITLE
Run creation without ghost

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#126]
The current implementation creates an empty run and then modifies it. This causes 'ghost' runs for other people on the system.
Make a proper implementation

**Comment by XCarrel** [comment]
Make it so that a new run form pops up on the run list page.
Same thing for modifications.
In fact, everything should be doable from one single page

**Comment by AlexandreJunod** [comment]
Fin in 7de7d3a
