### ISSUE TITLE
Runner resource

### ISSUE THREAD

**Issue by AntonioGiordano12** [CPNV-ES/Runners-Laravel#142]
Need to add an API route to get all the runners. Same as the RunnerResource. ("/api/runners")

**Comment by Dardanboy** [comment]
Spoken about it the 15th of february. Need to check if the informations returned can be filtered to get the last run for the user.

We found that myRuns was into RunResource instead of RunnerResource.

**Comment by Dardanboy** [comment]
Need to speak about it asap with the Runners (mobile) group so things are more clear (If possible on the 15th of March 2019).

**Comment by Dardanboy** [comment]
Discussed with the group on the 15th of March and concluded that they didn't need it anymore.
