### ISSUE TITLE
run_drivers status

### ISSUE THREAD

**Issue by AntonioGiordano12** [CPNV-ES/Runners-Laravel#143]
Make the status of run_drivers table working.
Only need a "finished" status for the mobile app, if the run is terminated.

**Comment by Dardanboy** [comment]
Can you say us if this is still available for the version right now or if it can be closed. 
If it's still a bug nowadays, please provide more informations about it (which link you use to have to replicate this bug)

**Comment by Dardanboy** [comment]
No more needed as discussed on the 15th of March
