### ISSUE TITLE
Handling of concurrent access over the API

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#144]
The API must pass the 'updated_at' field of a run.
When the mobile app requests an update of a run, it will provide this value, unmodified.
The backend compares the values in the database and in the request.
If they are the same, the request is accepted and the run is updated.
If they differ, it means that someone has modified the run since the last time the app read the run. The request is rejected.

**Comment by AlexandreJunod** [comment]
The work is done, but not pushed on develop. I'm waiting a response from the issue "Handle concurrent access #62" on the CPNV-ES/runners group.

https://github.com/CPNV-ES/runners/issues/62

**Comment by AlexandreJunod** [comment]
Fix in 61043ba
