### ISSUE TITLE
Check run state logic and correct if needed

### ISSUE THREAD

**Issue by Dardanboy** [CPNV-ES/Runners-Laravel#152]
On big screen, a run has appeared ready when there was not car set (with '?') to this run. This should not happen.

2 things could appear: 
- Logic is not good
- View is not good

Update @AlexandreJunod 
Show all the runs saved on the database, except "finished" and "drafting"

**Comment by AlexandreJunod** [comment]
Show all the runs saved on the database, except "finished" and "drafting"

**Comment by AlexandreJunod** [comment]
Fixed in 8c55086

**Comment by AlexandreJunod** [comment]
Fixed in 8c55086
