### ISSUE TITLE
Add vehicle list on route api/cars?filter=...

### ISSUE THREAD

**Issue by AlexandreJunod** [CPNV-ES/Runners-Laravel#154]
The API needs the list of the vehicles (id and name).

If possible sort by category. Example : Send all "Vito" vehicles when the category is "Vito".

Don't send a list of vehicles when the run is "finished", it could use too much resources and decrease the performances.

**Comment by Dardanboy** [comment]
Not sure to understand what is really requestedhere. Need to speak asap with the Runners (mobile) group about it (if possible on the 15th of March 2019)

**Comment by Dardanboy** [comment]
Discussed with the group on the 15th of March 2019. They said that they only needed the type of vehicle attached to the run in response. 

For example if the type of vehicle is VITO for the run, they only need to have the list of vito vehicles returned and not all like now.

We decided that they sent a request to the API containing the type of vehicle (`VITO`, `LIMO`, `MATOS`) and return all the vehicles attached to it (`Vito 1`, `Vito 2`...) when they are `available`.

**Comment by StevenAvelino** [comment]
The VITO filter seems to work, but the MATOS and LIMO always returns an empty array

**Comment by Dardanboy** [comment]
Fixed in 5c6e6b5
Added starts_at and ends_at possibility to filter cars that are available for those datetime range.
