### ISSUE TITLE
Refactor DB for statuses

### ISSUE THREAD

**Issue by AlexandreJunod** [CPNV-ES/Runners-Laravel#155]
The database currently uses a polymorphic relationship to assign a status, and we need to divide the statuses because no status are used in two places at the same time.

The tables need their own statuses.

**Comment by Dardanboy** [comment]
Actually (March 6th 2019), the Models below have been ported to their own status (without using statusable):

- [x] Car (Added CarStatus)
- [x] Run (Added RunStatus)


- The only model left with statusable is the User model

**Comment by Dardanboy** [comment]
Work in progress in  feature/replaceStatusableInUserModel for the User model

**Comment by Dardanboy** [comment]
Actually (March 7th 2019), the old status system that worked with polymorphic relations has been replaced with status table corresponding to the models: Car/Run/User

**Comment by Dardanboy** [comment]
Fixed in 29b7526
