### ISSUE TITLE
Fix the statuses sent to the mobile API

### ISSUE THREAD

**Issue by AlexandreJunod** [CPNV-ES/Runners-Laravel#163]
After the changes in the DB, the statuses aren't sent correctly.

The table "statuses" has been replaced by : 
  - user_statuses
  - run_statuses
  - car_statuses

Change the code who collect the data.

If possible try to send the statuses as object or text and not as array. This will prevent the mobile group from doing unnecessary things.

**Comment by Dardanboy** [comment]
Fixed in 4023042
