### ISSUE TITLE
Notification to driver

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#3]
Use case: driver takes a run -> run is ready to go -> someone pops at the desk and asks for a change -> coordinator applies it, but the driver doesn't know

**Comment by bastiennicoud** [comment]
Could be implemented with laravel included database notification system !?
[Database Notifications - laravel](https://laravel.com/docs/5.6/notifications#database-notifications)

**Comment by bastiennicoud** [comment]
Notifications are now implemented in the Runners back-end.
They are stored in database with laravel's notification system, and can be retrieved easily.
To use it in mobile app just add an api endpoint and mobile app compatibility.

**Comment by bastiennicoud** [comment]
The notifications are displayed in the back-office vie our profile menu. (need to be implemented in the mobile app).

**Comment by XCarrel** [comment]
Too complex (for now): we'll keep the good old phone call.
