### ISSUE TITLE
Redesign run details screen

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#32]
Change the top of the run details screen to match the following mockup:

![capture d ecran 2017-07-22 a 10 16 40](https://user-images.githubusercontent.com/7465241/28489712-6781661c-6ec9-11e7-97ae-0838cd4bc03d.png)

The + buttons add a waypoint after the one of the line it's on

**Comment by bastiennicoud** [comment]
OK in the v2.0.0-beta.3

**Comment by bastiennicoud** [comment]
Ok in v2.0.0-beta.3
