### ISSUE TITLE
Debug panel in runs

### ISSUE THREAD

**Issue by MisterX25** [CPNV-ES/Runners-Laravel#4]
The debug panel on the right must not appear in prod
![capture d ecran 2017-07-18 a 10 26 56](https://user-images.githubusercontent.com/7465241/28307599-b0d3b92e-6ba3-11e7-8864-8b97610549af.png)

**Comment by Grisou13** [comment]
The debug panel was removed from the whole build process. 
`v1.0.2-stable` was released. 
You can simply `git pull` to get the latest changes.

**Comment by MisterX25** [comment]
[cid:0D06E04F-C580-43BB-A8C2-B295E26E168B]
Le 18 juil. 2017 à 13:15, Thomas Ricci <notifications@github.com<mailto:notifications@github.com>> a écrit :


The debug panel was removed from the whole build process.
v1.0.2-stable was released.
You can simply git pull to get the latest changes.

**Comment by MisterX25** [comment]
Please let the submitter of the bug close it, when the fix has been validated.

Le 18 juil. 2017 à 13:15, Thomas Ricci <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #4<https://github.com/CPNV-ES/Runners-Laravel/issues/4>.

**Comment by MisterX25** [comment]
![capture d ecran 2017-07-18 a 13 32 58](https://user-images.githubusercontent.com/7465241/28315213-cd81ed24-6bbd-11e7-9d92-88cd5c7eb66d.png)

**Comment by Grisou13** [comment]
Have you tried clearing your browsers cache?
What browser are you running on?

**Comment by MisterX25** [comment]
Running on Chrome.
Cache cleared -> fixed it (sorry , should have thought of it)
