### ISSUE TITLE
API : Driver schedule

### ISSUE THREAD

**Issue by kayoumido** [CPNV-ES/Runners-Laravel#40]
We would need the API to return the hours at which a driver is working. (Schedule model)

e.g.
```
# Returns the current users working hours
/me/workinghours 

response :
[
    {
        "start" : DateTime, 
        "end" : DateTime
    },
    ...
]
```

This is rather important, so it would be great if you could get this done before the holidays.

**Comment by bastiennicoud** [comment]
Now working
