### ISSUE TITLE
API: Car comments

### ISSUE THREAD

**Issue by Grisou13** [CPNV-ES/Runners-Laravel#41]
As of right now the api doesn't return the comments for a car.
We need to get the comments for a car only on the car details

This means `/cars` **shouldn't** return the comments.
But `/cars/{id}` **should**. We can discuss if we need to put paramaters in the requestm but it would be nice if we didn't have to.

E.g
```
Request:

GET /cars/{id}

Response:

{
      id: <integer>
      name: <string>
      type: <VehicleType>
      plate_number: <string>
      nb_place: <integer>
      comments: [
            {
                  createdAt: <datetime>,
                message: <string>,
                author: <User>
            }
      ]
}
```

This isn't urgent, but when implemented, please notify us!

PS: There might not be any comments just because seeding doesn't generate any

**Comment by bastiennicoud** [comment]
Now working.
