### ISSUE TITLE
Driver's pictures

### ISSUE THREAD

**Issue by MisterX25** [CPNV-ES/Runners-Laravel#5]
Can't upload pictures for drivers (profile and license alike)

**Comment by MisterX25** [comment]
Video capture
[Bug upload image.mov.zip](https://github.com/CPNV-ES/Runners-Laravel/files/1155633/Bug.upload.image.mov.zip)

**Comment by Grisou13** [comment]
New permissions were put in place allowing coordinators and admin to change anybodies profile/license image
v1.0.2-stable was released.
You can simply git pull to get the latest changes.

**Comment by MisterX25** [comment]
[cid:13F50F71-DA5C-4C46-B672-15A0B0438CF4]
Le 18 juil. 2017 à 13:17, Thomas Ricci <notifications@github.com<mailto:notifications@github.com>> a écrit :


New permissions were put in place allowing coordinators and admin to change anybodies profile/license image
v1.0.2-stable was released.
You can simply git pull to get the latest changes.

**Comment by MisterX25** [comment]
![capture d ecran 2017-07-18 a 13 33 27](https://user-images.githubusercontent.com/7465241/28315197-bd4dda26-6bbd-11e7-89b9-d92749573d41.png)

**Comment by Grisou13** [comment]
So sorry, forgot to mesnion, you will need to reset the database, 
or if it not possible execute the following commands:
```
php artisan cache:forget spatie.permission.cache
php artisan tinker
# This will prompt you into an interactive php console
# type the folowing
Schema::disableForeignKeyConstraints()
collect(config("permission.table_names"))->values()->each(function($tname){DB::table($tname)->truncate();})
Schema::enableForeignKeyConstraints
exit
# now redo the roles and permissions
php artisan db:seed --class=RoleSeeder
```

**Comment by MisterX25** [comment]
Ok now, thanks
