### ISSUE TITLE
Interface cleanup

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#64]
Remove breadcrumb, copyright, versions from the common layout. Put all that in an About page linked from the logo

**Comment by bastiennicoud** [comment]
ok in the future beta 3.4

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)

**Comment by NicolasHenryCPNV** [comment]
The breadcrumb is removed on this commit 23e3b8d160e373f8728080612b45e76a35262d7e
Check it for more details.
