### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#65]
Correct the following spelling mistakes:

- inéxistant -> inexistant in /runs/x/edit
- Prét -> Prêt in /runs
- présisément -> précisément

**Comment by bastiennicoud** [comment]
Fixed in commit f7827c867bce981d2ef91190bb343719dcff1575

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)
