### ISSUE TITLE
Bad hint

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#66]
![capture d ecran 2018-06-13 a 08 58 37](https://user-images.githubusercontent.com/7465241/41335129-107f83b0-6ee8-11e8-9ab7-53d5b3db2db8.png)

**Comment by bastiennicoud** [comment]
Resolved in commit def7221ed10fac1bd4bf2b86165f1fb0d6698c4b

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)
