### ISSUE TITLE
Default run filters

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#69]
Default filters are fine when coming from the menu Runs>Afficher les runs, but not after a run deletion, nor when I click on 'Runs' in the menu bar

**Comment by bastiennicoud** [comment]
Fixed in commit ad4c1bcc721e1b35dd4afe710d0eda1f13d129fb

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)
