### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#70]
In the Run View (/runs/x), the links 'Afficher ...' don't work.
Make it only one link 'Plus d'info...' please

**Comment by bastiennicoud** [comment]
The section is groupped under the 'Plus d'infos...' in commit b40c1d2b01ef0bc4593df20a10242606972f48d0

**Comment by bastiennicoud** [comment]
You need to rebuilt the assets to use the 'Plus d'infos...' link.

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)
