### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#71]
The run status doesn't seem to be properly evaluated in some cases. See video attached
[runstatus.mp4.zip](https://github.com/CPNV-ES/Runners-Laravel/files/2097018/runstatus.mp4.zip)

**Comment by bastiennicoud** [comment]
#56

**Comment by bastiennicoud** [comment]
Fixed in 935ef7c07e25a3929677de6ccfe05d85f081237a

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)
