### ISSUE TITLE
Runner status

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#72]
I can't change the status of a runner anywhere !?!?

**Comment by XCarrel** [comment]
ATTENTION!! The status change must be done with a dropdown list, whose values must be fetched in a database table.
This table does NOT exist at this point (poor datamodel)

**Comment by bastiennicoud** [comment]
Added in [feature/status_managment](https://github.com/CPNV-ES/Runners-Laravel/tree/feature/status_managment)
