### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#73]
Remove the username everywhere, but particularly in the runner details page

**Comment by bastiennicoud** [comment]
Fixed in commit 7a599dfa8178632997d4a27f503d843ec5124aa4

**Comment by bastiennicoud** [comment]
OK in [v2.0.0-beta.3.4](https://github.com/CPNV-ES/Runners-Laravel/releases/tag/v2.0.0-beta.3.4)
