### ISSUE TITLE
Kiéla

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#80]
Avec les photos ça a vraiment de la gueule, mais on peut faire encore un poil mieux!

- Supprimer le message '43e Paléo Festival de Nyon Developpement'
- Agrandir la photo de ~50%
- Ne mettre que le prénom, sous la photo, dans une 'étiquette' à la couleur du groupe
- Aucun run attribué -> pas de texte
- Run futur -> 'Prochain run: Texarkana, 16h30'
- Run en cours -> 'Run en cours: Texarkana, 16h30'
- Ne pas afficher le status, sauf si c'est un status explicitement demandé (cela implique un champ style 'showInKiela' dans la table des status.

**Comment by bastiennicoud** [comment]
Last point linket to the #74 issue

**Comment by NicolasHenryCPNV** [comment]
Resolved in [feature/kielaUpdate](https://github.com/CPNV-ES/Runners-Laravel/tree/feature/kielaUpdate)
