### ISSUE TITLE
Adding driver in kiela fails

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#89]
![capture d ecran 2018-06-15 a 12 02 30](https://user-images.githubusercontent.com/7465241/41463139-a69f00a6-7095-11e8-8c7a-21421cbe7840.png)

**Comment by bastiennicoud** [comment]
Resolved in #90 issue. When you pull the next release, you need to run the **php artisan db:seed --class=FillUsersNameField** to repair the users table consistency.
