### ISSUE TITLE
Take Run (v2)

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/Runners-Laravel#99]
Need a new API endpoint allowing the driver to participate in a run with a specific role.
Example: run with a Limo, a Vito and a Matos vehicle. The mobile app will allow the user to select which vehicle he drives, so:

New endpoint: /runs/{runner}/driver

When I invoke it from my mobile, I am defined as the driver for the specific 'runner'

**Comment by bastiennicoud** [comment]
Ok, like #100 the route would be named as `/runners/{runner}/driver`

**Comment by bastiennicoud** [comment]
Added in commit c9534bd51487e0d6573f5898a4b6bf26ac3c0443
